#!/usr/bin/env bash

mkdir -p ~/Pictures
curl -o ~/Pictures/bg.png https://files.perpheads.com/BBLUKYaapCkNH6iy.png

if [[ ! -d i3-gaps-deb ]]; then
	git clone git@github.com:maestrogerardo/i3-gaps-deb.git
	RESULT=$?
	if [ $RESULT -ne 0 ]; then
		exit
	fi
fi

cd i3-gaps-deb
chmod +x i3-gaps-deb
sudo ./i3-gaps-deb
cd ..
sudo rm -rf i3-gaps-deb

sudo apt -y install i3status feh terminator neovim zip xclip jq scrot zsh ranger

# Install and setup oh-my-zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
sudo chsh -s $(which zsh)

# Install powerlevel10k
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
