#!/usr/bin/env bash
mkdir -p ~/.config/nvim/plugin
mkdir -p ~/.config/nvim/after/plugin
mkdir -p ~/.config/nvim/lua

# link everything
for f in `find . -regex ".*\.vim$\|.*\.lua$"`; do
    rm -rf ~/$f
    ln -s ~/dotfiles/$f ~/$f
done
